DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE TRANSACTION (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(200) NOT NULL,
    partner  VARCHAR(30)  NOT NULL,
    phone    VARCHAR(15)  NOT NULL,
    dateTime TIMESTAMP
);